name: Deploy with CodeDeploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Render task definition
        run: |
          sed -i "s|<IMAGE_URI>|${{ secrets.ECR_REPOSITORY_URI }}:latest|g" taskdef.json
          sed -i "s|REPLACE_AT_RUNTIME|${{ secrets.ECS_EXECUTION_ROLE_ARN }}|g" taskdef.json

      - name: Register task definition
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://taskdef.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Inject task definition into appspec
        run: |
          sed -i "s|<TASK_DEFINITION>|${{ env.TASK_DEF_ARN }}|g" appspec.yaml

      - name: Trigger CodeDeploy
        run: |
          APPSPEC=$(jq -Rs . < appspec.yaml)
          aws deploy create-deployment \
            --application-name karuna-strapi-codedeploy-app \
            --deployment-group-name karuna-strapi-deployment-group \
            --revision "revisionType=AppSpecContent,appSpecContent={content=$APPSPEC}"
