name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.5"

      - name: Terraform Init
        run: terraform -chdir=terraform init -reconfigure -input=false

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan -input=false \
            -var="ecr_repository_name=${{ secrets.ECR_REPOSITORY_NAME }}" \
            -var="db_name=${{ secrets.TF_VAR_db_name }}" \
            -var="db_username=${{ secrets.TF_VAR_db_username }}" \
            -var="db_password=${{ secrets.TF_VAR_db_password }}" \
            -var="strapi_admin_jwt_secret=${{ secrets.TF_VAR_strapi_admin_jwt_secret }}" \
            -var="strapi_api_token_salt=${{ secrets.TF_VAR_strapi_api_token_salt }}" \
            -var="strapi_app_keys=${{ secrets.TF_VAR_strapi_app_keys }}"

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var="ecr_repository_name=${{ secrets.ECR_REPOSITORY_NAME }}" \
            -var="db_name=${{ secrets.TF_VAR_db_name }}" \
            -var="db_username=${{ secrets.TF_VAR_db_username }}" \
            -var="db_password=${{ secrets.TF_VAR_db_password }}" \
            -var="strapi_admin_jwt_secret=${{ secrets.TF_VAR_strapi_admin_jwt_secret }}" \
            -var="strapi_api_token_salt=${{ secrets.TF_VAR_strapi_api_token_salt }}" \
            -var="strapi_app_keys=${{ secrets.TF_VAR_strapi_app_keys }}"

      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name karuna-strapi-codedeploy-app \
            --deployment-group-name karuna-strapi-deployment-group \
            --revision "gitHubLocation={repository=${{ github.repository }},commitId=${{ github.sha }}}" \
            --region ${{ secrets.AWS_REGION }}

      - name: Describe ECS Service
        run: |
          aws ecs describe-services \
            --cluster karuna-ecs-cluster \
            --services karuna-service \
            --region ${{ secrets.AWS_REGION }}
